#!/usr/bin/php
<?php
// Get path of this script. 
$path = dirname(__FILE__);

// Install Vim - Plug
exec("curl -fLo {$path}/vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim");

// Create some symlinks
exec("ln -s {$path}/bash_profile ~/.bash_profile");
exec("ln -s {$path}/bashrc ~/.bashrc");
exec("ln -s {$path}/vim ~/.vim");
exec("ln -s {$path}/vimrc ~/.vimrc");
